sudo: false
language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"

cache:
    directories:
        - ngrok

before_script:
    - curl -L "https://github.com/kward/shunit2/archive/source.tar.gz" | tar zx

script:
    - bash tests/acme_test.sh
