sudo: false
language: shell

cache:
    directories:
        - ngrok

before_script:
    - curl -L "https://github.com/kward/shunit2/archive/source.tar.gz" | tar zx

script:
    - bash tests/acme_test.sh
